name: release

on:
  push:
    tags:

jobs:

  docker-release:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - Dockerfile: build/Dockerfile
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          DATE=$(date +'%Y-%m-%d_%H-%M-%S')
          echo ::set-output name=full_tag_name::${TAG}
          echo ::set-output name=full_date_tag::${DATE}
          echo ::set-output name=latest_tag::latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and publish ${{ matrix.target.Dockerfile }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          file: ${{ matrix.target.Dockerfile }}
          platforms: linux/amd64,linux/arm64,linux/arm
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
          tags: |
            zc2638/drone-k8s-plugin:${{ steps.prepare.outputs.full_tag_name }}
            zc2638/drone-k8s-plugin:${{ steps.prepare.outputs.latest_tag }}
